<?php

/**
 * @file
 * Administration toolbar for quick access to top level administration items.
 */

// use Drupal\Core\Template\Attribute;

// /**
//  * Implements hook_preprocess_HOOK() for HTML document templates.
//  */
// function sticky_toolbar_preprocess_html(&$variables) {
//   if (!\Drupal::currentUser()->hasPermission('access toolbar')) {
//     return;
//   }

//   $variables['attributes'] = new Attribute($variables['attributes']);
//   $variables['attributes']->addClass('test')->removeClass(['toolbar-tray-open', 'toolbar-fixed']);
// }

function sticky_toolbar_preprocess_page(&$variables) {
  $variables['#attached']['library'][] =  'sticky_toolbar/sticky_toolbar_reset';
}